[tox]
envlist = 
    py-{std, ext}
labels = 
    format = format-{md, py}
    lint = format-{md, py}, lint
    build = clean, _build

[testenv]
package = wheel
dependency_groups  = 
    test
extras = 
    ext: extra
commands =
    coverage run -m pytest -rs {posargs}
    coverage report --include tests/*

[testenv:format-py]
skip_install = true
deps = 
    ruff
commands = 
    ruff check --select I --fix {posargs:.}
    ruff format {posargs:.}

[testenv:format-md]
skip_install = true
deps = 
    mdformat
commands = 
    mdformat {posargs:.}

[testenv:lint]
skip_install = true
deps = 
    ruff
commands =
    ruff check --fix {posargs:.}

[testenv:clean]
skip_install = true
deps = pyclean
commands = pyclean {posargs:. --debris --verbose}

[testenv:_build]
skip_install = true
allowlist_externals =
    uv
commands = 
    uv build --wheel --no-sources
