name: Publish to PyPI

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v10.1.0

      - name: Build release distributions
        run: |
          echo "SOURCE_DATE_EPOCH= $(git log -1 --pretty=%ct))" >> $GITHUB_ENV
          echo "SOURCE_DATE_EPOCH: $SOURCE_DATE_EPOCH"
          uv build --wheel --no-sources

      - name: Upload distributions
        uses: actions/upload-artifact@v7
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: 
      - release-build
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/project/overhead-log/${{ github.event.release.name }}

    steps:
      - uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist/

      - uses: astral-sh/setup-uv@v10.1.0

      - run: uv publish
